### ISSUE TITLE
driver.go: mssql semicolon delimited string format

### ISSUE THREAD

**Issue by simonwillcock** [chop-dbhi/sql-agent#4]
I'm not a Go developer, but I'm trying to get this working with the mssql driver and I'm wondering if there is a typo here in `strings.Join`:

```go
// MSSQL supports semicolon delimited key=value parameters.
// See https://github.com/denisenkom/go-mssqldb#connection-parameters
"mssql": func(params map[string]interface{}) string {
	toks := make([]string, len(params))
	i := 0

	for k, v := range params {
		toks[i] = fmt.Sprintf("%s=%v", k, v)
		i++
	}

	return strings.Join(toks, " ")
},
```
The comment above suggests that they should be semicolon delimited, but the strings.Join appears to be space delimiting them. Is that the case?

Cheers

**Comment by simonwillcock** [comment]
For context, I'm trying to get this working with your other great prometheus-sql project!

**Comment by bruth** [comment]
Hi @simonwillcock! Thanks for the report, it looks like you are correct per the driver documentation. I don't have an SQL Server database to test against, but I patched the code and pushed a new docker image with a commit tag:`dbhi/sql-agent:1fcc067` Can you pull it down and give it a try?

**Comment by simonwillcock** [comment]
Awesome, thanks! I should be able to give it a crack tomorrow and report back :)

**Comment by simonwillcock** [comment]
Ok that worked well! Thanks for making that change so quickly.

However, I found a couple of other issues related to the connection parameters that the go-mssqldb lib is expecting compared to the set of parameters that prometheus-sql has documented. 

I think the same function above should probably map the documented parameters to those expected by the the go-mssqldb library as follows:

- [`host` -> `server`](https://github.com/denisenkom/go-mssqldb/blob/05a5564207042f04d43d186d82e195a7f5699d48/tds.go#L944)
- [`user` -> `user id`](https://github.com/denisenkom/go-mssqldb/blob/05a5564207042f04d43d186d82e195a7f5699d48/tds.go#L954)

Fortunately your project just passes through all the parameters, so I could just specify the alternate keys in the .yml file, but for consistency it would probably make it easier for future users to map them automatically! 

Thanks again for this project and for responding so quickly for the issue above! Let me know if you want me to move this to a new issue or not.

**Comment by bruth** [comment]
Thanks for debugging this 😄  Here is the latest build `dbhi/sql-agent:2f937ce` which includes this mapping.

**Comment by simonwillcock** [comment]
Hey bruth, sorry for the delay. I've just given this a run using the default `user` and `host` parameters in the .yml, and it works a treat! 👍

**Comment by bruth** [comment]
Great! No problem at all. I will push out releases in a bit.
