### ISSUE TITLE
Missing dependecy: lib/pq (?)

### ISSUE THREAD

**Issue by PaulWalkerUK** [chop-dbhi/sql-agent#5]
I'm trying to build this on Windows (I don't have a Docker environment available to me). I'm getting this:

```
C:\Users\username\go\src\github.com\chop-dbhi\sql-agent\cmd\sql-agent>go install
main.go:15:2: cannot find package "github.com/lib/pq" in any of:
        C:\Users\username\go\src\github.com\chop-dbhi\sql-agent\cmd\sql-agent\vendor\github.com\lib\pq (vendor tree)
        C:\Go\src\github.com\lib\pq (from $GOROOT)
        C:\Users\username\go\src\github.com\lib\pq (from $GOPATH)
```

If I download the zip of the master branch from [https://github.com/lib/pq](https://github.com/lib/pq/tree/2704adc878c21e1329f46f6e56a1c387d788ff94) and put it in `C:\Users\username\go\src\github.com\chop-dbhi\sql-agent\cmd\sql-agent\vendor\github.com\lib\pq`, then the `install` completes, apparently successfully.

I don't know if this is happening because of the way I'm building it? I can submit a pull request if you want me to add `lib/pq` into the `/vendor` directory - is the current `master` branch the best one to use?

**Comment by bruth** [comment]
Hi @PaulWalkerUK. I figured it out! The `.gitignore` was ignoring `lib` which matches `lib/pq`. I only wanted a top-level `lib/` directory to be ignored. I pushed the fix and `lib/pq` is now in the `vendor/` directory. Sorry for the confusion!

**Comment by PaulWalkerUK** [comment]
Splendid, thank you!
