### ISSUE TITLE
Snowflake support

### ISSUE THREAD

**Issue by tomsej** [chop-dbhi/sql-agent#6]
Hi, could you please add support for Snowflake DB? Here is Golang Snowflake driver - https://github.com/snowflakedb/gosnowflake

**Comment by bruth** [comment]
@tomsej I pushed a Docker image with support for it using the driver: `dbhi/sql-agent:snowflake`. Can you please test this out prior to me merging in the changes?

**Comment by bruth** [comment]
Actually one second.. I think I constructed the DSN wrong.

**Comment by bruth** [comment]
Alright.. give it a whirl.

**Comment by tomsej** [comment]
Wooow you are really fast 👍. I have tried it and it seems that there is some kind of problem. When I run:
`curl -H "Content-Type: application/json" -X POST -d '{"driver": "snowflake", "connection": {"host": "xxxx","user": "xxxx", "database": "xxxx", "password": "xxxxx"},"sql": "SELECT * FROM xxxx.xxxx"}' http://localhost:5000`

I get following error:
`problem connecting to database: timeout. err: Post https://xxxxx.snowflakecomputing.com:443/session/v1/login-request?databaseName=XXX&requestId=requestId%1111111-111111-11111&schemaName=public: x509: failed to load system roots and no roots provided. Hanging?%`

Thought there is missing ca-certificates library in docker container but error appears after installation. Do you have any hint?

**Comment by bruth** [comment]
Hm. I took a suggestion from a few repos to install ca-certificates. Odd that I haven't not observed this before. Push a new image under the same tag, please try it out.

**Comment by bruth** [comment]
@tomsej Did you get a chance to try the second image I pushed?
